#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
set -euo pipefail

CONFIG_FILE="/data/config.toml"

# Boot-time options from the HA add-on UI.
REAL_HOST=$(bashio::config 'real_shelly_host')
REAL_PORT=$(bashio::config 'real_shelly_udp_port')
LOG_LEVEL=$(bashio::config 'log_level')

# Seed config.toml on first start. Subsequent edits via the web UI live
# in /data/config.toml and survive add-on updates (map: addon_config:rw).
if [ ! -f "${CONFIG_FILE}" ]; then
    bashio::log.info "No config.toml found — creating defaults from add-on options."
    cat > "${CONFIG_FILE}" <<EOF
# Generated by the HA add-on on first start.
# Edit further via the built-in web UI (Sidebar → Shelly Multiplexer).

[real_shelly]
host = "${REAL_HOST}"
udp_port = ${REAL_PORT}
poll_interval_ms = 500
request_timeout_ms = 1000

[virtual_shelly]
bind_interface = "0.0.0.0"
udp_port = 1010
# Set http_port = 80 (or another free port) only if you have inverters
# that talk to the Shelly via HTTP/REST (some Hoymiles models). Marstek
# Venus E and similar use UDP/1010 + mDNS only, so 0 keeps port 80 free
# on the HA host.
http_port = 0
min_sample_period_ms = 1000
device_mac = ""
device_hostname = ""
firmware = "1.4.4"

[management]
# Bound on all interfaces so the HA supervisor's watchdog probe (which
# lives in its own network namespace) can reach /api/health, and so
# Ingress can proxy the UI. The admin API has no auth — keep this on a
# trusted network or restrict at the firewall if your LAN isn't.
bind_address = "0.0.0.0:8080"

[dispatcher]
strategy = "equal"
rate_limit_w_per_s = 1000
deadband_w = 30

[safety]
max_total_w = 3000
acknowledged_higher_risk = false
acknowledged_separate_fuses = false
EOF
else
    bashio::log.info "Reusing existing /data/config.toml."
fi

export RUST_LOG="shelly_multiplexer=${LOG_LEVEL},${LOG_LEVEL}"
exec /usr/bin/shelly-multiplexer --config "${CONFIG_FILE}"
