#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
set -euo pipefail

CONFIG_FILE="/data/config.toml"

# Boot-time options from the HA add-on UI.
REAL_HOST=$(bashio::config 'real_shelly_host')
REAL_PORT=$(bashio::config 'real_shelly_udp_port')
LOG_LEVEL=$(bashio::config 'log_level')

# Seed config.toml on first start. Everything *except* the real_shelly
# host/port is then managed via the web UI; the host/port is passed as
# CLI args on every start so changes in the HA add-on Configuration tab
# always win and don't require deleting the file.
if [ ! -f "${CONFIG_FILE}" ]; then
    bashio::log.info "No config.toml found — creating defaults."
    cat > "${CONFIG_FILE}" <<EOF
# Generated by the HA add-on on first start. Edit further via the
# built-in web UI. real_shelly.host / udp_port are overridden by the
# add-on Configuration tab on every start — change them there.

[real_shelly]
host = "${REAL_HOST}"
udp_port = ${REAL_PORT}
poll_interval_ms = 500
request_timeout_ms = 1000

[virtual_shelly]
bind_interface = "0.0.0.0"
udp_port = 1010
# Set http_port = 80 (or another free port) only if you have inverters
# that talk to the Shelly via HTTP/REST (some Hoymiles models). Marstek
# Venus E and similar use UDP/1010 + mDNS only.
http_port = 0
min_sample_period_ms = 1000
device_mac = ""
device_hostname = ""
firmware = "1.4.4"
# HA OS runs Avahi on UDP/5353 already; running our own mdns-sd
# daemon on top conflicts with it and the worker thread dies. Leave
# this off unless you've stopped Avahi.
enable_mdns = false

[management]
bind_address = "0.0.0.0:8080"

[dispatcher]
strategy = "equal"
rate_limit_w_per_s = 1000
deadband_w = 30

[safety]
max_total_w = 3000
acknowledged_higher_risk = false
acknowledged_separate_fuses = false

[home_assistant]
# Set enabled = true and add `soc_entity_id = "sensor.xyz"` to a
# battery to read SoC from HA instead of polling the inverter
# directly — useful when an HA integration already owns the
# inverter's UDP port. The token is injected at runtime from
# \$SUPERVISOR_TOKEN, so leave it blank in the file.
enabled = false
url = "http://supervisor/core/api"
token = ""
timeout_ms = 3000
EOF
else
    bashio::log.info "Reusing existing /data/config.toml (real_shelly host/port from HA options)."
fi

export RUST_LOG="shelly_multiplexer=${LOG_LEVEL},${LOG_LEVEL}"
export RUST_BACKTRACE=1

bashio::log.info "Starting shelly-multiplexer (RUST_LOG=${RUST_LOG})…"

# Run instead of exec so we can capture and surface the exit reason
# in the add-on log when the binary crashes, instead of seeing only
# s6 stop the service.
set +e
/usr/bin/shelly-multiplexer \
    --config "${CONFIG_FILE}" \
    --real-shelly-host "${REAL_HOST}" \
    --real-shelly-udp-port "${REAL_PORT}"
EXIT=$?
set -e
bashio::log.error "shelly-multiplexer exited with status ${EXIT}"
exit "${EXIT}"
